apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ucdi1ks57-go
  janus-idp.io/tekton: ucdi1ks57-go
  backstage.io/kubernetes-id: ucdi1ks57-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ucdi1ks57-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
